WB_ACCOUNTS = [
    {
        "name": "WB Магазин 1",
        "token": "eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjYwOTAzdjEiLCJ0eXAiOiJKV1QifQ.eyJhY2MiOjEsImVudCI6MSwiZXhwIjoxODA1MTc1NDY2LCJpZCI6IjAxYTBhMGZmLTE1YzktN2JjMy1iMjQ4LTJjNmY4OTNmYzI0NSIsImlpZCI6MTMwNTc2NzU3LCJvaWQiOjQxODA3NTUsInMiOjE2LCJzaWQiOiIzMzkzNjBhNS04ZjBhLTRlMTktOGVjZC1jY2NmMjNjNTk2YmUiLCJ0IjpmYWxzZSwidWlkIjoxMzA1NzY3NTd9.XvGXlrbr98IrFGeXyp5heFdLuTNWZklkzBN9YE1tMRMJRPyMHaZvxiYJ-VUupa8SLaNYPJ6P55_92fJd5GrNyA",
    },
    {
        "name": "WB Магазин 2",
        "token": "eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjYwOTAzdjEiLCJ0eXAiOiJKV1QifQ.eyJhY2MiOjEsImVudCI6MSwiZXhwIjoxODA1MTc1NDk3LCJpZCI6IjAxYTBhMGZmLThjZTEtNzYxOS05NTc4LTQ0YWQ3OTVkZjlkYyIsImlpZCI6Mjg0MzkyMTgsIm9pZCI6MjgzMTgzLCJzIjoxNiwic2lkIjoiZWQxMzlhMzMtMmFmOS00N2YzLTgwOGItZGI4ZDNhOTFhZTBiIiwidCI6ZmFsc2UsInVpZCI6Mjg0MzkyMTh9.E867AnfxN_avZBfgExF0aXDmHGNvQjcXPJMVaAdd9y8SQnkSRLfe9uUoNRca-FUBUTEL9XiA0amJL5flRcLMjQ",
    }
]
